import Head from 'next/head'
import color_bg from '../public/Background_Staircase.jpg';
import bw_bg from '../public/BW_Background_Staircase.jpg';
import say_i_do from '../public/Say_I_Do.svg';
import { Playfair_Display_SC, DM_Sans, Raleway } from '@next/font/google';
import { keyframes } from '@emotion/react';
import styled from '@emotion/styled';

const headerFont = Playfair_Display_SC({
  weight: "400",
  subsets: ['latin'],
});

const dateFont = Raleway({
  weight: "600",
  subsets: ['latin'],
});

const linkFont = DM_Sans({
  weight: "400",
  subsets: ['latin'],
});

const fadingBgImage = keyframes`
  from {opacity: 1}
  to {opacity: 0}
`

const Header = styled.h1`
  font-family: ${headerFont.style.fontFamily};
  font-weight: ${headerFont.style.fontWeight};
  color: #2f482f;
  width: 100%;
  font-size: 3.5rem;
  margin: 0;
  text-align: right;
  line-height: 3rem;
`;

const Link = styled.a`
  font-family: ${linkFont.style.fontFamily};
  font-weight: ${linkFont.style.fontWeight};
  color: #2f482f;
  font-size: 1.25rem;
  text-align: right;
  margin-top: 0.5rem;
  display: inherit;
`

const BWBackground = styled.img`
  z-index: -1;
  position: absolute;
  height: 100vh;
  max-width: 50vw;
  @media (orientation: portrait) {
    max-width: 100vw;
    width: 100vw;
    object-fit: cover;
    background-position: center;
  }
`;

const ColorBackground = styled.img`
  z-index: -1;
  position: absolute;
  height: 100vh;
  max-width: 50vw;
  @media (orientation: portrait) {
    max-width: 100vw;
    width: 100vw;
    object-fit: cover;
    background-position: center;
  }
  animation: ${fadingBgImage}
    5s
    ease
    0s  
    alternate
    infinite
    none
    running;
`;

const DefaultBackground = styled.div`
  z-index: -3;
  position: absolute;
  height: 100vh;
  width: 100vw;
  background: #f3fff9;
`;

const Main = styled.main`
  display: flex;
  height: 100vh;
  flex-direction: column;
  background: rgba(0, 0, 0, 0);
  padding: .5rem;
  align-items: end;
`

const Date = styled.div`
  margin-top: auto;
  font-family: ${dateFont.style.fontFamily};
  color: #2f482f;
  font-size: 2rem;
`

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultBackground />
      <BWBackground src={bw_bg.src} />
      <ColorBackground src={color_bg.src} />
      <Main>
        <div style={{display: 'flex', flexDirection: 'column', padding: ''}}></div>
        <Header>Maddi &<br/>Brandon</Header>
        <img style={{width: '16rem'}} src={say_i_do.src} />
        <Link href="/">Our Story</Link>
        <Link href="/">Party</Link>
        <Link href="/">Registration</Link>
        <Link href="/">RSVP</Link>
        <Date>
          <div>05</div>
          <div>13</div>
          <div>23</div>
        </Date>
      </Main>
    </div>
  )
}
